
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[mouse]

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[general]
live_config_reload = true

[terminal]

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#00ced1"
green = "#19c68a"
magenta = "#8e44ad"
red = "#ff4040"
white = "#808080"
yellow = "#fdbc4b"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#00ffff"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.normal]
black = "#232627"
blue = "#1d99f3"
cyan = "#00ced1"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#63686d"
yellow = "#f67400"

[colors.primary]
background = "#10100E"
foreground = "#C6C6C4"

[colors.selection]
background = "#d8dee9"
text = "#191919"

[cursor]
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"

[font.offset]
x = -1
y = -1

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>	'''

[terminal.shell]
args = ["new-session"]
program = "/usr/bin/tmux"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
#gtk_theme_variant = "dark"
opacity = 0.5
title = "Alacritty"

[window.padding]
x = 2
y = 2

[keyboard]
